services:
  # Se utiliza contenedor aparte para nginx-proxy y letsencrypt.

  # nginx-proxy:
  #   image: nginxproxy/nginx-proxy
  #   container_name: nginx-proxy
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - certs:/etc/nginx/certs
  #     - vhost:/etc/nginx/vhost.d
  #     - html:/usr/share/nginx/html
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #   restart: always

  # letsencrypt:
  #   image: nginxproxy/acme-companion
  #   container_name: nginx-letsencrypt
  #   depends_on:
  #     - nginx-proxy
  #   environment:
  #     NGINX_PROXY_CONTAINER: nginx-proxy
  #   volumes:
  #     - certs:/etc/nginx/certs
  #     - vhost:/etc/nginx/vhost.d
  #     - html:/usr/share/nginx/html
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   restart: always

  jardinconecta-api:
    image: ghcr.io/galbornozdev/jardinconecta-api:latest
    #build:
      # context: ./JardinConecta
      # dockerfile: Dockerfile
    container_name: jardinconecta-api
    depends_on:
      - postgres
    environment:
      # proxy + ssl
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      VIRTUAL_PORT: ${API_PORT}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      Application__BaseUrl: "${APPLICATION_BASE_URL}"
      LogLevel__Default: "Warning"
      ConnectionStrings__Default: "Host=postgres;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      SendGrid__ApiKey: ${SENDGRID_API_KEY}
      SendGrid__FromEmail: ${SENDGRID_FROM_EMAIL}
      Twilio__AccountSid: ${TWILIO_ACCOUNT_SID}
      Twilio__AuthToken: ${TWILIO_AUTH_TOKEN}
      Twilio__FromPhone: ${TWILIO_FROM_PHONE}
      Firebase__ProjectId: ${FIREBASE_PROJECT_ID}
      Firebase__PrivateKeyId: ${FIREBASE_PRIVATE_KEY_ID}
      Firebase__PrivateKey: ${FIREBASE_PRIVATE_KEY}
      Firebase__ClientEmail: ${FIREBASE_CLIENT_EMAIL}
      Firebase__ClientId: ${FIREBASE_CLIENT_ID}
      Jwt__Key: ${JWT_KEY}
    volumes:
      - media_data:/app/media
    expose:
      - "8080"
    networks:
      - proxy
    restart: always

  postgres:
    image: postgres:16
    container_name: jardinconecta-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - proxy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  proxy:
    external: true

volumes:
  postgres_data:
  media_data:
  # certs:
  # vhost:
  # html: