CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Infantes" (
    "Id" uuid NOT NULL,
    "Nombre" character varying(100) NOT NULL,
    "Apellido" character varying(100) NOT NULL,
    "Documento" character varying(50),
    "PhotoUrl" text,
    "FechaNacimiento" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Infantes" PRIMARY KEY ("Id")
);

CREATE TABLE "Jardines" (
    "Id" uuid NOT NULL,
    "Nombre" character varying(100) NOT NULL,
    CONSTRAINT "PK_Jardines" PRIMARY KEY ("Id")
);

CREATE TABLE "Roles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Descripcion" character varying(200) NOT NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE "RolesSala" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Descripcion" character varying(200) NOT NULL,
    CONSTRAINT "PK_RolesSala" PRIMARY KEY ("Id")
);

CREATE TABLE "TiposTutelas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Descripcion" character varying(50) NOT NULL,
    CONSTRAINT "PK_TiposTutelas" PRIMARY KEY ("Id")
);

CREATE TABLE "Salas" (
    "Id" uuid NOT NULL,
    "Nombre" character varying(100) NOT NULL,
    "IdJardin" uuid NOT NULL,
    CONSTRAINT "PK_Salas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Salas_Jardines_IdJardin" FOREIGN KEY ("IdJardin") REFERENCES "Jardines" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Usuarios" (
    "Id" uuid NOT NULL,
    "Email" character varying(254) NOT NULL,
    "PasswordHash" character varying(500) NOT NULL,
    "FechaAlta" timestamp with time zone NOT NULL,
    "FechaModificacion" timestamp with time zone NOT NULL,
    "FechaBaja" timestamp with time zone,
    "IdRol" integer NOT NULL,
    "IdJardin" uuid,
    "CaracteristicaPais" character varying(3),
    "CodigoArea" character varying(6),
    "Numero" character varying(20),
    CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Usuarios_Jardines_IdJardin" FOREIGN KEY ("IdJardin") REFERENCES "Jardines" ("Id"),
    CONSTRAINT "FK_Usuarios_Roles_IdRol" FOREIGN KEY ("IdRol") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Personas" (
    "IdUsuario" uuid NOT NULL,
    "Nombre" character varying(100) NOT NULL,
    "Apellido" character varying(100) NOT NULL,
    "Documento" character varying(50),
    "PhotoUrl" text,
    CONSTRAINT "PK_Personas" PRIMARY KEY ("IdUsuario"),
    CONSTRAINT "FK_Personas_Usuarios_IdUsuario" FOREIGN KEY ("IdUsuario") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Tutelas" (
    "IdInfante" uuid NOT NULL,
    "IdUsuario" uuid NOT NULL,
    "IdTipoTutela" integer NOT NULL,
    "EsPrincipal" boolean NOT NULL,
    "FechaAlta" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Tutelas" PRIMARY KEY ("IdInfante", "IdUsuario"),
    CONSTRAINT "FK_Tutelas_Infantes_IdInfante" FOREIGN KEY ("IdInfante") REFERENCES "Infantes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Tutelas_TiposTutelas_IdTipoTutela" FOREIGN KEY ("IdTipoTutela") REFERENCES "TiposTutelas" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Tutelas_Usuarios_IdUsuario" FOREIGN KEY ("IdUsuario") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Usuarios_Salas_Roles" (
    "IdUsuario" uuid NOT NULL,
    "IdSala" uuid NOT NULL,
    "IdRolSala" integer NOT NULL,
    CONSTRAINT "PK_Usuarios_Salas_Roles" PRIMARY KEY ("IdUsuario", "IdSala", "IdRolSala"),
    CONSTRAINT "FK_Usuarios_Salas_Roles_RolesSala_IdRolSala" FOREIGN KEY ("IdRolSala") REFERENCES "RolesSala" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Usuarios_Salas_Roles_Salas_IdSala" FOREIGN KEY ("IdSala") REFERENCES "Salas" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Usuarios_Salas_Roles_Usuarios_IdUsuario" FOREIGN KEY ("IdUsuario") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
);

INSERT INTO "Roles" ("Id", "Descripcion")
VALUES (10, 'Usuario');
INSERT INTO "Roles" ("Id", "Descripcion")
VALUES (20, 'Admin Jardin');
INSERT INTO "Roles" ("Id", "Descripcion")
VALUES (30, 'Admin Sistema');

INSERT INTO "RolesSala" ("Id", "Descripcion")
VALUES (1, 'Familiar');
INSERT INTO "RolesSala" ("Id", "Descripcion")
VALUES (2, 'Educador');

INSERT INTO "TiposTutelas" ("Id", "Descripcion")
VALUES (1, 'Madre');
INSERT INTO "TiposTutelas" ("Id", "Descripcion")
VALUES (2, 'Padre');
INSERT INTO "TiposTutelas" ("Id", "Descripcion")
VALUES (3, 'Tutor');

CREATE INDEX "IX_Salas_IdJardin" ON "Salas" ("IdJardin");

CREATE INDEX "IX_Tutelas_IdTipoTutela" ON "Tutelas" ("IdTipoTutela");

CREATE INDEX "IX_Tutelas_IdUsuario" ON "Tutelas" ("IdUsuario");

CREATE INDEX "IX_Usuarios_IdJardin" ON "Usuarios" ("IdJardin");

CREATE INDEX "IX_Usuarios_IdRol" ON "Usuarios" ("IdRol");

CREATE INDEX "IX_Usuarios_Salas_Roles_IdRolSala" ON "Usuarios_Salas_Roles" ("IdRolSala");

CREATE INDEX "IX_Usuarios_Salas_Roles_IdSala" ON "Usuarios_Salas_Roles" ("IdSala");

SELECT setval(
    pg_get_serial_sequence('"Roles"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Roles") + 1,
        nextval(pg_get_serial_sequence('"Roles"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"RolesSala"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "RolesSala") + 1,
        nextval(pg_get_serial_sequence('"RolesSala"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"TiposTutelas"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "TiposTutelas") + 1,
        nextval(pg_get_serial_sequence('"TiposTutelas"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251124164212_InitialMigration', '8.0.22');

COMMIT;


START TRANSACTION;

CREATE TABLE "Comunicados" (
    "Id" uuid NOT NULL,
    "Titulo" text NOT NULL,
    "Contenido" text NOT NULL,
    "IdUsuarioRemitente" uuid NOT NULL,
    "IdSala" uuid NOT NULL,
    CONSTRAINT "PK_Comunicados" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Comunicados_Salas_IdSala" FOREIGN KEY ("IdSala") REFERENCES "Salas" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Comunicados_Usuarios_IdUsuarioRemitente" FOREIGN KEY ("IdUsuarioRemitente") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Comunicados_Usuarios_Destino" (
    "ComunicadosId" uuid NOT NULL,
    "UsuariosDestinatariosId" uuid NOT NULL,
    CONSTRAINT "PK_Comunicados_Usuarios_Destino" PRIMARY KEY ("ComunicadosId", "UsuariosDestinatariosId"),
    CONSTRAINT "FK_Comunicados_Usuarios_Destino_Comunicados_ComunicadosId" FOREIGN KEY ("ComunicadosId") REFERENCES "Comunicados" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Comunicados_Usuarios_Destino_Usuarios_UsuariosDestinatarios~" FOREIGN KEY ("UsuariosDestinatariosId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Comunicados_IdSala" ON "Comunicados" ("IdSala");

CREATE INDEX "IX_Comunicados_IdUsuarioRemitente" ON "Comunicados" ("IdUsuarioRemitente");

CREATE INDEX "IX_Comunicados_Usuarios_Destino_UsuariosDestinatariosId" ON "Comunicados_Usuarios_Destino" ("UsuariosDestinatariosId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251124202012_CreateTable-Comunicado', '8.0.22');

COMMIT;