// <auto-generated />
using System;
using System.Collections.Generic;
using JardinConecta.Infrastructure.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JardinConecta.Migrations
{
    [DbContext(typeof(ServiceContext))]
    [Migration("20260224114635_CreateTable_ComunicadoArchivo")]
    partial class CreateTable_ComunicadoArchivo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JardinConecta.Models.Entities.Comunicado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Contenido");

                    b.Property<string>("ContenidoTextoPlano")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdSala")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Titulo");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdSala");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Comunicados", (string)null);
                });

            modelBuilder.Entity("JardinConecta.Models.Entities.ComunicadoArchivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("IdComunicado")
                        .HasColumnType("uuid");

                    b.Property<string>("NombreArchivoOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("IdComunicado");

                    b.ToTable("ComunicadosArchivos", (string)null);
                });

            modelBuilder.Entity("JardinConecta.Models.Entities.ComunicadoView", b =>
                {
                    b.Property<Guid>("IdComunicado")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdComunicado", "IdUsuario");

                    b.HasIndex("IdUsuario");

                    b.ToTable("ComunicadosViews", (string)null);
                });

            modelBuilder.Entity("JardinConecta.Models.Entities.Infante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Apellido");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Documento")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Documento");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaNacimiento");

                    b.Property<Guid>("IdJardin")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Nombre");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("PhotoUrl");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdJardin");

                    b.ToTable("Infantes", (string)null);
                });

            modelBuilder.Entity("JardinConecta.Models.Entities.Jardin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Nombre");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Jardines", (string)null);
                });

            modelBuilder.Entity("JardinConecta.Models.Entities.Persona", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Apellido");

                    b.Property<string>("Documento")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Documento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Nombre");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("PhotoUrl");

                    b.HasKey("IdUsuario");

                    b.ToTable("Personas", (string)null);
                });

            modelBuilder.Entity("JardinConecta.Models.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Descripcion");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Familia"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Educador"
                        });
                });

            modelBuilder.Entity("JardinConecta.Models.Entities.Sala", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdJardin")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Nombre");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdJardin");

                    b.ToTable("Salas", (string)null);
                });

            modelBuilder.Entity("JardinConecta.Models.Entities.TipoTutela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Descripcion");

                    b.HasKey("Id");

                    b.ToTable("TiposTutelas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Madre"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Padre"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Tutor"
                        });
                });

            modelBuilder.Entity("JardinConecta.Models.Entities.TipoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Descripcion");

                    b.HasKey("Id");

                    b.ToTable("TiposUsuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Descripcion = "Usuario"
                        },
                        new
                        {
                            Id = 20,
                            Descripcion = "Admin Jardin"
                        },
                        new
                        {
                            Id = 30,
                            Descripcion = "Admin Sistema"
                        });
                });

            modelBuilder.Entity("JardinConecta.Models.Entities.Tutela", b =>
                {
                    b.Property<Guid>("IdInfante")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdTipoTutela")
                        .HasColumnType("integer");

                    b.HasKey("IdInfante", "IdUsuario");

                    b.HasIndex("IdTipoTutela");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Tutelas", (string)null);
                });

            modelBuilder.Entity("JardinConecta.Models.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("Email");

                    b.Property<Guid?>("IdJardin")
                        .HasColumnType("uuid");

                    b.Property<int>("IdTipoUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("PasswordHash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty<Dictionary<string, object>>("Telefono", "JardinConecta.Models.Entities.Usuario.Telefono#Telefono", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("CaracteristicaPais")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("CaracteristicaPais");

                            b1.Property<string>("CodigoArea")
                                .HasMaxLength(6)
                                .HasColumnType("character varying(6)")
                                .HasColumnName("CodigoArea");

                            b1.Property<string>("Numero")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Numero");
                        });

                    b.HasKey("Id");

                    b.HasIndex("IdJardin");

                    b.HasIndex("IdTipoUsuario");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("JardinConecta.Models.Entities.UsuarioSalaRol", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdSala")
                        .HasColumnType("uuid");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdUsuario", "IdSala", "IdRol");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdSala");

                    b.ToTable("Usuarios_Salas_Roles", (string)null);
                });

            modelBuilder.Entity("JardinConecta.Models.Entities.Comunicado", b =>
                {
                    b.HasOne("JardinConecta.Models.Entities.Sala", "Sala")
                        .WithMany()
                        .HasForeignKey("IdSala")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JardinConecta.Models.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sala");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("JardinConecta.Models.Entities.ComunicadoArchivo", b =>
                {
                    b.HasOne("JardinConecta.Models.Entities.Comunicado", "Comunicado")
                        .WithMany("ComunicadoArchivos")
                        .HasForeignKey("IdComunicado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comunicado");
                });

            modelBuilder.Entity("JardinConecta.Models.Entities.ComunicadoView", b =>
                {
                    b.HasOne("JardinConecta.Models.Entities.Comunicado", "Comunicado")
                        .WithMany("ComunicadoViews")
                        .HasForeignKey("IdComunicado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JardinConecta.Models.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comunicado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("JardinConecta.Models.Entities.Infante", b =>
                {
                    b.HasOne("JardinConecta.Models.Entities.Jardin", "Jardin")
                        .WithMany("Infantes")
                        .HasForeignKey("IdJardin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jardin");
                });

            modelBuilder.Entity("JardinConecta.Models.Entities.Persona", b =>
                {
                    b.HasOne("JardinConecta.Models.Entities.Usuario", "Usuario")
                        .WithOne("Persona")
                        .HasForeignKey("JardinConecta.Models.Entities.Persona", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("JardinConecta.Models.Entities.Sala", b =>
                {
                    b.HasOne("JardinConecta.Models.Entities.Jardin", "Jardin")
                        .WithMany("Salas")
                        .HasForeignKey("IdJardin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jardin");
                });

            modelBuilder.Entity("JardinConecta.Models.Entities.Tutela", b =>
                {
                    b.HasOne("JardinConecta.Models.Entities.Infante", "Infante")
                        .WithMany("Tutelas")
                        .HasForeignKey("IdInfante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JardinConecta.Models.Entities.TipoTutela", "TipoTutela")
                        .WithMany()
                        .HasForeignKey("IdTipoTutela")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JardinConecta.Models.Entities.Usuario", "Usuario")
                        .WithMany("Tutelas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Infante");

                    b.Navigation("TipoTutela");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("JardinConecta.Models.Entities.Usuario", b =>
                {
                    b.HasOne("JardinConecta.Models.Entities.Jardin", "Jardin")
                        .WithMany()
                        .HasForeignKey("IdJardin");

                    b.HasOne("JardinConecta.Models.Entities.TipoUsuario", "TipoUsuario")
                        .WithMany()
                        .HasForeignKey("IdTipoUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jardin");

                    b.Navigation("TipoUsuario");
                });

            modelBuilder.Entity("JardinConecta.Models.Entities.UsuarioSalaRol", b =>
                {
                    b.HasOne("JardinConecta.Models.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JardinConecta.Models.Entities.Sala", "Sala")
                        .WithMany("UsuariosSalasRoles")
                        .HasForeignKey("IdSala")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JardinConecta.Models.Entities.Usuario", "Usuario")
                        .WithMany("UsuariosSalasRoles")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Sala");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("JardinConecta.Models.Entities.Comunicado", b =>
                {
                    b.Navigation("ComunicadoArchivos");

                    b.Navigation("ComunicadoViews");
                });

            modelBuilder.Entity("JardinConecta.Models.Entities.Infante", b =>
                {
                    b.Navigation("Tutelas");
                });

            modelBuilder.Entity("JardinConecta.Models.Entities.Jardin", b =>
                {
                    b.Navigation("Infantes");

                    b.Navigation("Salas");
                });

            modelBuilder.Entity("JardinConecta.Models.Entities.Sala", b =>
                {
                    b.Navigation("UsuariosSalasRoles");
                });

            modelBuilder.Entity("JardinConecta.Models.Entities.Usuario", b =>
                {
                    b.Navigation("Persona");

                    b.Navigation("Tutelas");

                    b.Navigation("UsuariosSalasRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
