name: Deploy to Droplet

on:
  workflow_call:
    inputs:
      trigger-deploy:
        required: true
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /opt/JardinConecta.API
            # Baja la última imagen del registry y recrea solo el contenedor API
            docker compose up -d --force-recreate --pull always jardinconecta-api